# 🐼 Complete Pandas Practice Notebook
### Taught the way a teacher would explain it in class — every line commented

Welcome! This notebook is built like a real classroom lesson.
Every code cell has comments explaining **what** we are doing and **why**.
Read the explanation, run the cell, look at the output, then move to the next one.

**How to use this notebook:**
1. Run cells in order (Shift + Enter).
2. Read every comment — that's the "teacher talking" part.
3. At the end of each section there are **Practice Exercises** for students to solve themselves (with hints, no answers given, so they actually learn).

Let's begin! 🚀

## 0️⃣ Setup — Importing Pandas

Before doing anything, we must import the pandas library.
We always import it with the short name `pd` — this is a universal convention,
every pandas user in the world does this, so your code looks familiar to everyone.

In [1]:
# Import pandas and give it the nickname 'pd'
# (This is the standard convention used by 99% of data scientists)
import pandas as pd
import numpy as np   # numpy is often used alongside pandas for numeric operations

# Let's check the version we are using (good habit before starting any project)
print("Pandas version:", pd.__version__)

Pandas version: 3.0.5

## 1️⃣ Pandas Series — The Building Block

A **Series** is just a single column of data, like one column in Excel.
It has:
- **values** (the actual data)
- an **index** (labels for each value, like row numbers)

Think of it as a smart list.

In [2]:
# Creating a Series from a normal Python list
# pandas automatically creates an index 0,1,2,3... for us
marks = pd.Series([85, 90, 78, 92, 88])

print(marks)
print()
print("Data type of marks:", type(marks))

0    85
1    90
2    78
3    92
4    88
dtype: int64

Data type of marks: <class 'pandas.Series'>

In [3]:
# We can give our own custom index (labels) instead of 0,1,2,3...
# Here we use student names as the index
marks_named = pd.Series([85, 90, 78, 92, 88],
                         index=["Ali", "Sara", "Bilal", "Ayesha", "Zain"])

print(marks_named)
print()

# Accessing a single value using its label (just like a dictionary!)
print("Sara's marks:", marks_named["Sara"])

Ali       85
Sara      90
Bilal     78
Ayesha    92
Zain      88
dtype: int64

Sara's marks: 90

### 📝 Practice Exercise 1
1. Create a Series called `prices` with 5 fruit prices: `[50, 120, 30, 200, 75]`
2. Give it a custom index of fruit names: `["Apple", "Mango", "Banana", "Grapes", "Orange"]`
3. Print the price of "Mango" only
4. Print the **average** price using `.mean()`

*(Write your code in the empty cell below)*

In [4]:
# 👉 Student: write your Exercise 1 solution here
prices = pd.Series([50, 120, 30, 200, 75],
              index =["Apple","Mango","Banana","Grapes","Orange"])
print(prices)
print()

print("price of Mango :" , prices["Mango"])

print("Average price :" , prices.mean())

Apple      50
Mango     120
Banana     30
Grapes    200
Orange     75
dtype: int64

price of Mango : 120
Average price : 95.0

## 2️⃣ DataFrame — The Real Power of Pandas

A **DataFrame** is a full table — many rows and many columns, just like an Excel sheet
or a SQL table. This is what you will use 90% of the time in real projects.

We can build a DataFrame from a Python **dictionary**, where:
- each **key** becomes a column name
- each **value** (a list) becomes the data in that column

In [5]:
# Creating a DataFrame using a dictionary
data = {
    "Name":   ["Ali", "Sara", "Bilal", "Ayesha", "Zain"],
    "Age":    [20, 22, 21, 23, 20],
    "City":   ["Lahore", "Karachi", "Faisalabad", "Islamabad", "Multan"],
    "Marks":  [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)

# Always print/display your DataFrame to check it looks correct
df

     Name  Age        City  Marks
0     Ali   20      Lahore     85
1    Sara   22     Karachi     90
2   Bilal   21  Faisalabad     78
3  Ayesha   23   Islamabad     92
4    Zain   20      Multan     88

In [6]:
# .head() shows the first 5 rows (very useful for big datasets)
# .tail() shows the last 5 rows
print("First 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

First 3 rows:
    Name  Age        City  Marks
0    Ali   20      Lahore     85
1   Sara   22     Karachi     90
2  Bilal   21  Faisalabad     78

Last 2 rows:
     Name  Age       City  Marks
3  Ayesha   23  Islamabad     92
4    Zain   20     Multan     88

In [7]:
# .info() gives a summary: column names, data types, non-null counts
# This is usually the FIRST thing a real data analyst runs on new data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [8]:
# .describe() gives statistical summary of NUMERIC columns only
# count, mean, std (standard deviation), min, max, and quartiles
df.describe()

            Age      Marks
count   5.00000   5.000000
mean   21.20000  86.600000
std     1.30384   5.458938
min    20.00000  78.000000
25%    20.00000  85.000000
50%    21.00000  88.000000
75%    22.00000  90.000000
max    23.00000  92.000000

In [9]:
# .shape tells us (rows, columns) -> very quick way to know dataset size
print("Shape of dataframe (rows, columns):", df.shape)

# .columns tells us the column names
print("Column names:", df.columns.tolist())

# .dtypes tells us the data type of each column
print("\nData types:\n", df.dtypes)

Shape of dataframe (rows, columns): (5, 4)
Column names: ['Name', 'Age', 'City', 'Marks']

Data types:
 Name       str
Age      int64
City       str
Marks    int64
dtype: object

### 📝 Practice Exercise 2
1. Create a DataFrame `students` with columns: `Name`, `Subject`, `Score` (5 rows, your own data)
2. Print `.info()` and `.describe()` of it
3. Print only the shape and column names

*(Write your code below)*

In [10]:
# 👉 Student: write your Exercise 2 solution here
students = {
    "Name" : ["Ayesha","Ali","Adil","Daniyal","Asad"],
    "Subject" : ["chem","bio","eng","comp","physics"],
    "Score" : ["90","85","75","78","65"],
    "Age":    [20, 22, 21, 23, 20],
    "City":   ["Lahore", "Karachi", "Faisalabad", "Islamabad", "Multan"],
    "Marks":  [85, 90, 78, 92, 88]
}
df = pd.DataFrame(students)

df

df.info()

df.describe()

print("shape of dataframe :" ,df.shape)

print("column names :" , df.columns.tolist())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Subject  5 non-null      str
 2   Score    5 non-null      str
 3   Age      5 non-null      int64
 4   City     5 non-null      str
 5   Marks    5 non-null      int64
dtypes: int64(2), str(4)
memory usage: 372.0 bytes
shape of dataframe : (5, 6)
column names : ['Name', 'Subject', 'Score', 'Age', 'City', 'Marks']

## 3️⃣ Selecting Rows & Columns

This is the MOST used skill in pandas. There are 2 main ways:
- `df['column']` → select one column
- `df.loc[]` → select by **label**
- `df.iloc[]` → select by **position number** (like array indexing)

In [11]:
# Selecting a SINGLE column -> returns a Series
print(df["Name"])
print(type(df["Name"]))  # Notice: single column = Series

0     Ayesha
1        Ali
2       Adil
3    Daniyal
4       Asad
Name: Name, dtype: str
<class 'pandas.Series'>

In [12]:
# Selecting MULTIPLE columns -> pass a LIST of column names -> returns a DataFrame
print(df[["Name" ,"Marks"]])
print(type(df[["Name","Marks"]])) # Notice: multiple columns = DataFrame

      Name  Marks
0   Ayesha     85
1      Ali     90
2     Adil     78
3  Daniyal     92
4     Asad     88
<class 'pandas.DataFrame'>

In [13]:
# .loc -> select rows/columns by LABEL (index name / column name)
# Syntax: df.loc[row_label, column_label]

# Get row with index 2 (Bilal's row)
print(df.loc[2])

print()

# Get specific rows and specific columns
print(df.loc[0:2, ["Name", "Score"]])   # rows 0 to 2 (inclusive!), only Name & Marks columns

Name             Adil
Subject           eng
Score              75
Age                21
City       Faisalabad
Marks              78
Name: 2, dtype: object

     Name Score
0  Ayesha    90
1     Ali    85
2    Adil    75

In [14]:
# .iloc -> select rows/columns by POSITION (integer index, like normal lists)
# Syntax: df.iloc[row_position, column_position]

print(df.iloc[0])          # first row
print()
print(df.iloc[0:3, 0:2])   # first 3 rows, first 2 columns (end is EXCLUSIVE here, unlike .loc)

Name       Ayesha
Subject      chem
Score          90
Age            20
City       Lahore
Marks          85
Name: 0, dtype: object

     Name Subject
0  Ayesha    chem
1     Ali     bio
2    Adil     eng

### ⚠️ Teacher's Tip (Important Gotcha!)
- `.loc` → label-based, **end index is INCLUDED**
- `.iloc` → position-based, **end index is EXCLUDED** (like normal Python slicing)

This confuses every beginner at least once — now you know it in advance! 😉

### 📝 Practice Exercise 3
Using the `df` created earlier:
1. Select only the `City` and `Age` columns
2. Select the row for "Ayesha" using `.loc`
3. Select the first 2 rows and first 3 columns using `.iloc`

In [15]:
print(df[["City","Age"]])

print(df.loc[0])

print(df.iloc[0:2 , 0:3])

         City  Age
0      Lahore   20
1     Karachi   22
2  Faisalabad   21
3   Islamabad   23
4      Multan   20
Name       Ayesha
Subject      chem
Score          90
Age            20
City       Lahore
Marks          85
Name: 0, dtype: object
     Name Subject Score
0  Ayesha    chem    90
1     Ali     bio    85

## 4️⃣ Filtering Data (Boolean Indexing)

This is how we ask pandas: *"Give me only the rows where a condition is TRUE"*
This is one of the most powerful and commonly used features in pandas.

In [16]:
# Filter: students who scored more than 85
high_scorers = df[df["Marks"] > 85]
print(high_scorers)

      Name  Subject Score  Age       City  Marks
1      Ali      bio    85   22    Karachi     90
3  Daniyal     comp    78   23  Islamabad     92
4     Asad  physics    65   20     Multan     88

In [17]:
# Combine multiple conditions
# Use & for AND, | for OR — and ALWAYS wrap each condition in ( )

# Students older than 20 AND marks above 80
result = df[(df["Age"] > 20) & (df["Marks"] > 80)]
print(result)

      Name Subject Score  Age       City  Marks
1      Ali     bio    85   22    Karachi     90
3  Daniyal    comp    78   23  Islamabad     92

In [18]:
# .isin() -> check if value is inside a list of options
cities_wanted = df[df["City"].isin(["Lahore", "Karachi"])]
print(cities_wanted)

     Name Subject Score  Age     City  Marks
0  Ayesha    chem    90   20   Lahore     85
1     Ali     bio    85   22  Karachi     90

### 📝 Practice Exercise 4
1. Filter students from `df` whose `Age` is less than 22
2. Filter students whose `City` is "Lahore" OR "Multan"
3. Filter students with `Marks` between 80 and 90 (use `&`)

In [19]:
# 👉 Student: write your Exercise 4 solution here

filter_students = df[df["Age"]< 22]
print(filter_students)

cities = df[df["City"].isin(["Lahore","Multan"])]
print(cities)

Markss = df[(df["Marks"]>80) & (df["Marks"]< 90)]
print(Markss)

     Name  Subject Score  Age        City  Marks
0  Ayesha     chem    90   20      Lahore     85
2    Adil      eng    75   21  Faisalabad     78
4    Asad  physics    65   20      Multan     88
     Name  Subject Score  Age    City  Marks
0  Ayesha     chem    90   20  Lahore     85
4    Asad  physics    65   20  Multan     88
     Name  Subject Score  Age    City  Marks
0  Ayesha     chem    90   20  Lahore     85
4    Asad  physics    65   20  Multan     88

## 5️⃣ Adding, Modifying & Dropping Columns

Real datasets are rarely perfect — you'll constantly need to create new columns,
update existing ones, or remove ones you don't need.

In [20]:
# Adding a NEW column: Grade based on Marks
# We use a simple condition here; later we'll use apply() for more complex logic
df["Passed"] = df["Marks"] >= 80   # This creates a column of True/False
print(df)

      Name  Subject Score  Age        City  Marks  Passed
0   Ayesha     chem    90   20      Lahore     85    True
1      Ali      bio    85   22     Karachi     90    True
2     Adil      eng    75   21  Faisalabad     78   False
3  Daniyal     comp    78   23   Islamabad     92    True
4     Asad  physics    65   20      Multan     88    True

In [21]:
# apply() lets us run a custom function on every value in a column
def get_grade(marks):
    # A simple grading function
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    else:
        return "C"

# axis is not needed here since we're applying to a single column (Series)
df["Grade"] = df["Marks"].apply(get_grade)
print(df)

      Name  Subject Score  Age        City  Marks  Passed Grade
0   Ayesha     chem    90   20      Lahore     85    True     B
1      Ali      bio    85   22     Karachi     90    True     A
2     Adil      eng    75   21  Faisalabad     78   False     C
3  Daniyal     comp    78   23   Islamabad     92    True     A
4     Asad  physics    65   20      Multan     88    True     B

In [22]:
# Dropping a column -> use drop(), specify axis=1 (columns) or columns=[...]
# NOTE: by default this does NOT change the original df unless inplace=True
df_dropped = df.drop(columns=["Passed"])
print(df_dropped)

print()
print("Original df still has 'Passed' column:")
print(df.columns.tolist())

      Name  Subject Score  Age        City  Marks Grade
0   Ayesha     chem    90   20      Lahore     85     B
1      Ali      bio    85   22     Karachi     90     A
2     Adil      eng    75   21  Faisalabad     78     C
3  Daniyal     comp    78   23   Islamabad     92     A
4     Asad  physics    65   20      Multan     88     B

Original df still has 'Passed' column:
['Name', 'Subject', 'Score', 'Age', 'City', 'Marks', 'Passed', 'Grade']

In [23]:
# Renaming columns
df_renamed = df.rename(columns={"Marks": "Score", "Name": "Student_Name"})
print(df_renamed.columns.tolist())

['Student_Name', 'Subject', 'Score', 'Age', 'City', 'Score', 'Passed', 'Grade']

### 📝 Practice Exercise 5
1. Add a new column `Age_in_5_years` = current Age + 5
2. Add a column `City_Upper` that has the city name in UPPERCASE (hint: `.str.upper()`)
3. Drop the `City` column and save it as a new dataframe `df_no_city`

In [24]:
# 👉 Student: write your Exercise 5 solution here
df["Age_in_5_years"] = df["Age"] + 5
print(df)

df["City_uppercase"] = df["City"].str.upper()
print(df)

df_no_city = df.drop(columns=["City"])
print("df_no_city")

      Name  Subject Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem    90   20      Lahore     85    True     B
1      Ali      bio    85   22     Karachi     90    True     A
2     Adil      eng    75   21  Faisalabad     78   False     C
3  Daniyal     comp    78   23   Islamabad     92    True     A
4     Asad  physics    65   20      Multan     88    True     B

   Age_in_5_years
0              25
1              27
2              26
3              28
4              25
      Name  Subject Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem    90   20      Lahore     85    True     B
1      Ali      bio    85   22     Karachi     90    True     A
2     Adil      eng    75   21  Faisalabad     78   False     C
3  Daniyal     comp    78   23   Islamabad     92    True     A
4     Asad  physics    65   20      Multan     88    True     B

   Age_in_5_years City_uppercase
0              25         LAHORE
1              27        KARACHI
2              26     FAISALABAD
3              28      ISLAMABAD
4              25         MULTAN
df_no_city

## 6️⃣ Sorting and Grouping (GroupBy = Superpower)

`groupby()` is one of the most powerful pandas tools — it lets us group rows
by a category and calculate summary statistics for each group (like Excel Pivot Tables).

In [25]:
# Sorting by a single column (ascending by default)
sorted_df = df.sort_values("Marks", ascending=False)  # highest marks first
print(sorted_df)

      Name  Subject Score  Age        City  Marks  Passed Grade  \
3  Daniyal     comp    78   23   Islamabad     92    True     A
1      Ali      bio    85   22     Karachi     90    True     A
4     Asad  physics    65   20      Multan     88    True     B
0   Ayesha     chem    90   20      Lahore     85    True     B
2     Adil      eng    75   21  Faisalabad     78   False     C

   Age_in_5_years City_uppercase
3              28      ISLAMABAD
1              27        KARACHI
4              25         MULTAN
0              25         LAHORE
2              26     FAISALABAD

In [26]:
# Sorting by MULTIPLE columns
sorted_multi = df.sort_values(["Grade", "Marks"], ascending=[True, False])
print(sorted_multi)

      Name  Subject Score  Age        City  Marks  Passed Grade  \
3  Daniyal     comp    78   23   Islamabad     92    True     A
1      Ali      bio    85   22     Karachi     90    True     A
4     Asad  physics    65   20      Multan     88    True     B
0   Ayesha     chem    90   20      Lahore     85    True     B
2     Adil      eng    75   21  Faisalabad     78   False     C

   Age_in_5_years City_uppercase
3              28      ISLAMABAD
1              27        KARACHI
4              25         MULTAN
0              25         LAHORE
2              26     FAISALABAD

In [27]:
# groupby() example: average marks PER grade
grouped = df.groupby("Grade")["Marks"].mean()
print(grouped)

print()

# groupby with multiple statistics at once using .agg()
grouped_stats = df.groupby("Grade")["Marks"].agg(["mean", "min", "max", "count"])
print(grouped_stats)

Grade
A    91.0
B    86.5
C    78.0
Name: Marks, dtype: float64

       mean  min  max  count
Grade
A      91.0   90   92      2
B      86.5   85   88      2
C      78.0   78   78      1

### 📝 Practice Exercise 6
1. Sort `df` by `Age` in ascending order
2. Group by `City` and find the average `Marks` per city
3. Group by `Grade` and count how many students are in each grade (`.count()`)

In [28]:
# 👉 Student: write your Exercise 6 solution here
sortt_df= df.sort_values(["Age"],ascending=True)
print(sortt_df)

grouping = df.groupby("City")["Marks"].mean()
print(grouping)

counting_grade = df.groupby("Grade").agg(["count"])
print(counting_grade)

      Name  Subject Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem    90   20      Lahore     85    True     B
4     Asad  physics    65   20      Multan     88    True     B
2     Adil      eng    75   21  Faisalabad     78   False     C
1      Ali      bio    85   22     Karachi     90    True     A
3  Daniyal     comp    78   23   Islamabad     92    True     A

   Age_in_5_years City_uppercase
0              25         LAHORE
4              25         MULTAN
2              26     FAISALABAD
1              27        KARACHI
3              28      ISLAMABAD
City
Faisalabad    78.0
Islamabad     92.0
Karachi       90.0
Lahore        85.0
Multan        88.0
Name: Marks, dtype: float64
       Name Subject Score   Age  City Marks Passed Age_in_5_years  \
      count   count count count count count  count          count
Grade
A         2       2     2     2     2     2      2              2
B         2       2     2     2     2     2      2              2
C         1       1     1     1     1     1      1              1

      City_uppercase
               count
Grade
A                  2
B                  2
C                  1

## 7️⃣ Handling Missing Data

Real-world data is messy — it almost always has missing values (`NaN`).
Knowing how to detect and handle them is a critical skill.

In [29]:
# Let's create a messy dataset with some missing values
messy_data = {
    "Name": ["Ali", "Sara", "Bilal", "Ayesha", np.nan],
    "Marks": [85, np.nan, 78, 92, 88],
    "City": ["Lahore", "Karachi", np.nan, "Islamabad", "Multan"]
}
messy_df = pd.DataFrame(messy_data)
print(messy_df)

     Name  Marks       City
0     Ali   85.0     Lahore
1    Sara    NaN    Karachi
2   Bilal   78.0        NaN
3  Ayesha   92.0  Islamabad
4     NaN   88.0     Multan

In [30]:
# Detect missing values -> returns True/False for each cell
print(messy_df.isnull())

print()

# Count missing values PER COLUMN (very commonly used!)
print("Missing values per column:")
print(messy_df.isnull().sum())

    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4   True  False  False

Missing values per column:
Name     1
Marks    1
City     1
dtype: int64

In [31]:
# Option 1: Drop rows that have ANY missing value
cleaned_drop = messy_df.dropna()
print("After dropna():")
print(cleaned_drop)

After dropna():
     Name  Marks       City
0     Ali   85.0     Lahore
3  Ayesha   92.0  Islamabad

In [32]:
# Option 2: Fill missing values instead of dropping them
# Fill missing Marks with the average of the column (common technique!)
filled_df = messy_df.copy()
filled_df["Marks"] = filled_df["Marks"].fillna(filled_df["Marks"].mean())
filled_df["City"] = filled_df["City"].fillna("Unknown")

print("After fillna():")
print(filled_df)

After fillna():
     Name  Marks       City
0     Ali  85.00     Lahore
1    Sara  85.75    Karachi
2   Bilal  78.00    Unknown
3  Ayesha  92.00  Islamabad
4     NaN  88.00     Multan

### 📝 Practice Exercise 7
1. Count how many missing values exist in each column of `messy_df`
2. Fill missing `Name` values with the string `"Unknown Student"`
3. Create a new dataframe that drops rows only if `Marks` is missing (hint: `subset=["Marks"]`)

In [33]:
# 👉 Student: write your Exercise 7 solution here

print("missing values per column :")
print(messy_df.isnull().sum())

filled_df["Name"] = filled_df["Name"].fillna("Unknown name")
print(filled_df)  

new_df = df.dropna(subset=["Marks"])
print(new_df)

missing values per column :
Name     1
Marks    1
City     1
dtype: int64
           Name  Marks       City
0           Ali  85.00     Lahore
1          Sara  85.75    Karachi
2         Bilal  78.00    Unknown
3        Ayesha  92.00  Islamabad
4  Unknown name  88.00     Multan
      Name  Subject Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem    90   20      Lahore     85    True     B
1      Ali      bio    85   22     Karachi     90    True     A
2     Adil      eng    75   21  Faisalabad     78   False     C
3  Daniyal     comp    78   23   Islamabad     92    True     A
4     Asad  physics    65   20      Multan     88    True     B

   Age_in_5_years City_uppercase
0              25         LAHORE
1              27        KARACHI
2              26     FAISALABAD
3              28      ISLAMABAD
4              25         MULTAN

## 8️⃣ Reading & Writing Files (CSV)

In real jobs, you rarely type data manually — you load it from files.
The most common format is **CSV** (Comma Separated Values).

In [34]:
# Save our DataFrame to a CSV file (index=False avoids saving the row numbers too)
df.to_csv("students.csv", index=False)
print("File saved successfully!")

# Now let's read it back
df_from_csv = pd.read_csv("students.csv")
print(df_from_csv)

File saved successfully!
      Name  Subject  Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem     90   20      Lahore     85    True     B
1      Ali      bio     85   22     Karachi     90    True     A
2     Adil      eng     75   21  Faisalabad     78   False     C
3  Daniyal     comp     78   23   Islamabad     92    True     A
4     Asad  physics     65   20      Multan     88    True     B

   Age_in_5_years City_uppercase
0              25         LAHORE
1              27        KARACHI
2              26     FAISALABAD
3              28      ISLAMABAD
4              25         MULTAN

### 📝 Practice Exercise 8
1. Save `messy_df` to a file called `messy_students.csv`
2. Read it back into a new variable called `check_df`
3. Print `check_df.head()`

In [35]:
# 👉 Student: write your Exercise 8 solution here

df.to_csv ("messy_students.csv", index=False)
print("File saved successfully")

check_df = pd.read_csv("messy_students.csv")
print(check_df)

print (check_df.head())

File saved successfully
      Name  Subject  Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem     90   20      Lahore     85    True     B
1      Ali      bio     85   22     Karachi     90    True     A
2     Adil      eng     75   21  Faisalabad     78   False     C
3  Daniyal     comp     78   23   Islamabad     92    True     A
4     Asad  physics     65   20      Multan     88    True     B

   Age_in_5_years City_uppercase
0              25         LAHORE
1              27        KARACHI
2              26     FAISALABAD
3              28      ISLAMABAD
4              25         MULTAN
      Name  Subject  Score  Age        City  Marks  Passed Grade  \
0   Ayesha     chem     90   20      Lahore     85    True     B
1      Ali      bio     85   22     Karachi     90    True     A
2     Adil      eng     75   21  Faisalabad     78   False     C
3  Daniyal     comp     78   23   Islamabad     92    True     A
4     Asad  physics     65   20      Multan     88    True     B

   Age_in_5_years City_uppercase
0              25         LAHORE
1              27        KARACHI
2              26     FAISALABAD
3              28      ISLAMABAD
4              25         MULTAN

## 🏆 Final Challenge — Put It All Together

Using everything you learned above, complete this mini real-world task:

**Scenario:** You are given exam results for a class. Do the following:

1. Create a DataFrame with columns: `Name`, `Math`, `Science`, `English` (at least 6 students, your own data)
2. Add a new column `Total` = sum of the 3 subjects
3. Add a new column `Average` = Total / 3
4. Add a new column `Result` = "Pass" if Average >= 40 else "Fail" (use `.apply()`)
5. Sort students by `Total` in descending order
6. Find the topper (student with the highest Total) using `.loc` and `.idxmax()`
7. Save the final DataFrame to `final_results.csv`

*(This combines Series, DataFrame creation, new columns, apply, sorting, and file I/O — everything from this notebook!)*

In [36]:
# 👉 Student: write your Final Challenge solution here
section = {
    "Name" : ["sadia" ,"haleema","khadija","ayesha","hafsa","salma"],
    "Maths" : [89,75,78,88,90,96],
    "Science" :[67,87,64,75,76,97],
    "English" :[93,85,55,56,78,98]
}

df= pd.DataFrame(section)

df

df['Total']=df['Maths'] + df['Science'] + df['English']

df

df['Average'] = df['Total'] / 3
df 

def get_result(average):
    if average >= 40 :
        return "Pass"
    else :
        return "fail"

df["Result"] = df['Average'].apply(get_result)

print(df)

sortttt = df.sort_values(['Total'] , ascending=False)
print(sortttt)

higher = df.iloc[df["Average"].idxmax()]
print(higher)

df.to_csv ("final_results.csv", index=False)
print("File saved successfully")

      Name  Maths  Science  English  Total    Average Result
0    sadia     89       67       93    249  83.000000   Pass
1  haleema     75       87       85    247  82.333333   Pass
2  khadija     78       64       55    197  65.666667   Pass
3   ayesha     88       75       56    219  73.000000   Pass
4    hafsa     90       76       78    244  81.333333   Pass
5    salma     96       97       98    291  97.000000   Pass
      Name  Maths  Science  English  Total    Average Result
5    salma     96       97       98    291  97.000000   Pass
0    sadia     89       67       93    249  83.000000   Pass
1  haleema     75       87       85    247  82.333333   Pass
4    hafsa     90       76       78    244  81.333333   Pass
3   ayesha     88       75       56    219  73.000000   Pass
2  khadija     78       64       55    197  65.666667   Pass
Name       salma
Maths         96
Science       97
English       98
Total        291
Average     97.0
Result      Pass
Name: 5, dtype: object
File saved successfully

---
## 🎉 Congratulations!

If you completed all the exercises above, you now know:
- ✅ Series & DataFrames
- ✅ Selecting data (`loc`, `iloc`, column selection)
- ✅ Filtering with conditions
- ✅ Adding/modifying/dropping columns
- ✅ `apply()` for custom logic
- ✅ Sorting & `groupby()`
- ✅ Handling missing data
- ✅ Reading/writing CSV files

**Next steps:** try `pd.merge()`, `pivot_table()`, and working with real Kaggle datasets!

*Made with ❤️ for learning Pandas — practice daily, and you'll master it fast.*